### ISSUE TITLE
error with refresh_rate

### ISSUE THREAD

**Issue by rchaput** [SuperPrower/i3lock-fancier#11]
Hi there,
On my computer the clock is not refreshing, except when I type something. I digged a little and found that the variable `refresh_rate` had an incorrect value. This seems to be due to the fact you are declaring it as `extern float`, and then initialize it as a `double`. Plus, you use `%lf` to write it (which is used for doubles). 

Replacing `double refresh_rate = 1.0;` by `float refresh_rate = 1.0` (settings.c line 50) and `ini_sget(config, "clock", "refresh_rate", "%lf", &refresh_rate);` by `ini_sget(config, "clock", "refresh_rate", "%f", &refresh_rate);` (settings.c line 293) solved the problem.

(I assume here that a float is enough for this variable. If not, you can replace `extern float refresh_rate;` with `extern double refresh_rate;`, settings.h line 43, instead).

**Comment by SuperPrower** [comment]
Thank you! I really thought it was issue with i3lock itself. It was my first big project in C, and I sure messed up a lot. Could you please make pull request or something? I really don't have any time even to make this small push to this project right now because of the exams, but I don't want this issue to hang until summer.
